# Generated by Django 6.0.4 on 2026-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirmationtoken'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_email',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_phone',
        ),
        migrations.RemoveConstraint(
            model_name='emailconfirmationtoken',
            name='unique_email_confirmation_token',
        ),
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
